### PR TITLE
Add TSM integration to display market prices in the main tooltip

### PR DESCRIPTION
**Pull request by zmsl**

### CODE REVIEW

**Comment by SacredDuckwhale** [comment]
Thanks for your contribution! I'll probably make some stylistic... adjustments, but otherwise I am hoping to integrate this with the next release.

Have you thought about showing prices for caged pets? I don't have time to look into adding this myself right now, but it would certainly make the feature considerably more useful.

**Comment by zmsl** [comment]
Yes, I've got some code that I'm waiting to test out.

**Comment by SacredDuckwhale** [comment]
Excellent! Should I wait for you to amend this PR or would it be easier to integrate this and then create a new PR for the added functionality?

**Comment by zmsl** [comment]
Let's integrate and I can work off of your "stylistic" changes :)

**Comment by zmsl** [comment]
And honestly, I'm a C# developer by profession so I'm very familiar with
programming concepts... but lua is brand new to me and in some ways a mind
fuck. I'll be able to learn by looking at your tweaks.

**Comment by SacredDuckwhale** [comment]
It appears I can't submit changes to your fork (it's an option you have to set - see [this link](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/)), so I pulled your changes and edited them in a separate branch: https://github.com/SacredDuckwhale/Rarity/tree/feature-tsm4-integration

---

Most of my proposed adjustments aren't specific to Lua, but rather stylistic changes or git-specific to hopefully improve the codebase's quality (over time. It's ancient and, frankly, a huge mess in some parts, but that doesn't mean it can't get worse).

You can see in the commit history what I did. So far I've only fixed some key issues and left the remainder as is. A few things that I would normally do:

* I'd usually add some comments to explain (for posterity) what is actually going on, though that is a question of personal style. I value maintainability very highly, which is why I tend to write much more than strictly necessary.
* I would also change the commit title and possibly add some message text in order to maintain a clean(-ish) history. In this case I'll just leave it be and add changes as separate commits since there isn't a published guideline for contributing at this time. Generally, being consistent is important, so the first commit should probably be titled differently.
* Other than that, some commits combine multiple changes, which makes it difficult to revert them individually. I am in fact too lazy right now to do this, which is why I added my changes on top (at the cost of clarity in the commit history). Indentation fixes, localization updates etc. I'd always commit separately. I suppose with larger projects this would be a moot point, since PRs are often squashed, but I'm relying on (no-fast-forward) merges to preserve history for the most part.
* The text for the TSM display could be rephrased to make clear what is actually being displayed  (Market Price etc.). That can wait, however, until the feature is more or less complete.
* I'd avoid to submit PRs that are originating from the forked master branch, as that'll result in highly ambiguous merge commits ("Merge x/master", which could mean anything) . General "best practice" is to create an aptly-named feature branch and then merge that when everything is ready (after rebasing it onto the then-current master branch and solving any merge conflicts)

---

Ultimately, I think the feature could be extended or changed as follows if you consider it useful:

* Different gold string formats: TSM style as coins, with thousands separator? Might have to be localized...  I'd see if I can get TSM to do all of this and use their settings if possible
* Also consider pet cages, as mentioned earlier in this thread
* Use TSM Localization for their own phrases (much easier and more reliable, plus a decent chance of getting a solid translation more or less automatically)

This is obviously optional, but might make the feature even more useful.

**Comment by SacredDuckwhale** [comment]
I've integrated these changes with some minor adustments in 9d55e3bfb8bf7011fe57c65f4bb8baa9c0d52611. I'm closing this as resolved, while moving possible improvements to a separate issue (#75).

Thanks for your contribution!

**Pull request closed without merging**
