### PR TITLE
Shadowlands release items

### PR DESCRIPTION
**Pull request by godejord**
Ref #216. I have composed an updated database containing all mounts and most toys listed in the issue. This is not a finished update but a functional work-in-progress. The majority of the items included works 100%, allthough a few require additional handling and/or are missing pieces of information like questid to track daily progress.

This also includes a fix to THE_MAW mapid as well as activating the SHADOWLANDS category within the addon.

EDIT: Added full list of included items and those that are not fully complete

> * [ ]  Mounts
>   
>   * [x]  Drops
>     
>     * [x] [Need questid]  https://www.wowhead.com/item=184167/mawsworn-soulhunter
>     * [x]  https://www.wowhead.com/item=180461/horrid-dredwing#comments
>     * [x] https://www.wowhead.com/item=181819/marrowfangs-reins#comments
>     * [x]  https://www.wowhead.com/item=182080/predatory-plagueroc
>     * [x]  https://www.wowhead.com/item=182083/bonecleavers-skullboar#comments
>     * [x]  https://www.wowhead.com/item=180582/endmire-flyer-tether
>     * [x]  https://www.wowhead.com/item=182085/blisterback-bloodtusk
>     * [x]  https://www.wowhead.com/item=182084/gorespine
>     * [x]  https://www.wowhead.com/item=182079/slime-covered-reins-of-the-hulking-deathroc
>     * [x]  https://www.wowhead.com/item=181815/armored-bonehoof-tauralus#comments
>     * [x] [SPECIAL - needs own logic]  https://www.wowhead.com/item=182075/bonehoof-tauralus
>     * [x]  https://www.wowhead.com/item=180730/wild-glimmerfur-prowler
>     * [x] [SPECIAL - needs own logic]  https://www.wowhead.com/item=184062/gnawed-reins-of-the-battle-bound-warhound
>     * [x] https://www.wowhead.com/item=181818/chewed-reins-of-the-callow-flayedwing
>     * [x]  https://www.wowhead.com/item=184160/bulbous-necroray
>     * [x]  https://www.wowhead.com/item=184162/pestilent-necroray
>     * [x]  https://www.wowhead.com/item=184161/infested-necroray
>     * [x]  https://www.wowhead.com/item=180762/phalynx-of-humility
>   * [x]  Paragon
>     
>     * [x] https://www.wowhead.com/item=182081/reins-of-the-colossal-slaughterclaw
>     * [x] https://www.wowhead.com/item=183800/amber-ardenmoth
>
> * [x]  Toys
>   
>   * [x]  Drops
>     
>     * [x] https://www.wowhead.com/item=184312/borr-geths-fiery-brimstone
>     * [x] https://www.wowhead.com/item=184292/ancient-elethium-coin
>     * [x] https://www.wowhead.com/item=181794/oropheas-lyre
>     * [x] https://www.wowhead.com/item=180873/smolderheart
>     * [x] https://www.wowhead.com/item=184476/regenerating-slime-vial
>     * [x] https://www.wowhead.com/item=184418/acrobatic-steward
>     * [x] https://www.wowhead.com/item=184404/ever-abundant-hearth
>     * [x] https://www.wowhead.com/item=184413/mnemonic-attunement-pane
>     * [x] https://www.wowhead.com/item=184415/soothing-vesper
>   * [x]  Paragon
>     
>     * [x] https://www.wowhead.com/item=184396/malfunctioning-goliath-gauntlet
>     * [x] https://www.wowhead.com/item=184495/infested-arachnid-casing
>     * [x] https://www.wowhead.com/item=184435/mark-of-purity

### CODE REVIEW

**Comment by SacredDuckwhale** [comment]
Thank you for your tremendous effort! It's greatly appreciated.

I suggest creating a separate issue for the missing items, and one for each of the individual SPECIAL cases. I'll look into the Theater of Pain bosses shortly, but I'm unclear on what the problem with Tahonta is/was. Can you please specify?

Either way, unless you want to add the pets to this PR also I guess it could be merged already, with the remaining issues being sorted out separately?

**Comment by nickbayley** [comment]
With regards to Tahonta, from what I've been reading, the mount will only drop if your active covenant is Necrolord. So I guess the logic for incrementing your attempts should only trigger when you are Necrolord.

This is unconfirmed though, just what wowhead is reporting right.

**Comment by SacredDuckwhale** [comment]
Oh, right. But doesn't that restriction apply to other items, as well? I figured custom logic was needed to filter out attempts if the player isn't aligned with the correct covenant.

**Comment by nickbayley** [comment]
I'm not entirely sure if there are other items like this Tahonta one. I've not encountered any.

There are a bunch of rares which can only be spawned by a member of a particular covenant, but I am fairly sure that these **do not** have a restriction on other players of different covenants from looting the items.

**Comment by godejord** [comment]
Good morning to you both. What @nickbayley is saying here is my understanding and experience so far as well. Tahonta will only drop for players linked with Necrolord, and this seems to be the only case where this restriction applies. There are other cases of 'drop only for X', but those are restricte in such a way that players with Y covenant will not even have a chance to interact with the thing that triggers the drop. In most cases X is required to spawn a NPC, but the item will drop for anyone that tags the NPC once it's there.

It would be nice to have a way to figure out the players covenant and a way to flag items that will require this prerequisite. I would not be surprised if more items like this are added in upcoming patches.


As for the remaining items, I am continously working on those. I have already commited several pets to the same branch, but if you want to merge right away and create a separate issue/PR for those, it's all the same to me.

**Pull request merged**
