### PR TITLE
Added WoD Timewalking instances to Infinite Timereaver list

### PR DESCRIPTION
**Pull request by redpandamonium**
Fixes issue #84

### CODE REVIEW

**Comment by SacredDuckwhale** [comment]
This is very helpful, thanks! Due to the code format changes the PR can't be merged without conflicts, so I've manually added it to the latest alpha.

One more question, though: Aren't there encounters where the boss survives when defeated, such as Yalnu? If so, the detection may not work unless special handling is added for those, usually via statistics (see OnCriteriaComplete() in Core.lua).

I can't test this currently and I'm also not very familiar with all the WOD dungeons, so I might be wrong.

**Comment by redpandamonium** [comment]
I have tested this and have not found a boss where the counting does not work. There is one case that could go wrong which would probably require some core code. On the iron docks there is a fight with 3 bosses. If you kill the main one and wipe it would have counted that one. I couldn't find a mechanism in your addon to require multiple bosses for a count.

**Comment by SacredDuckwhale** [comment]
Excellent. I'll add that part as a potential inaccuracy to the respective issue, but I don't believe adding more code for this fringe case would be reasonable (and in any case I can't test it right now as my account is inactive).

If you happen to run the dungeon with the debug log enabled, or use /rarity dump right after defeating that particular boss, you should see something along the lines of "Detected achievement criteria completion: <id>" - If there's one for this encounter then that could be added as a special case to the OnCriteriaComplete() function I mentioned, so that it'll count an attempt after the encounter was defeated.

**Comment by SacredDuckwhale** [comment]
Added in e92a547cff5d78f40419e261bcebc927625a231a :)

**Pull request closed without merging**
