### PR TITLE
DB: Added holidayTexture for missing Holiday related items

### LINKED ISSUE #289: Review holiday items to make sure they're using the proper holiday texture (for calendar-based notification)
In reviewing the item database, I've noticed that there's a lot of holiday items that don't appear to have their ``holidayTexture`` set (e.g., Big Love Rocket). If I understand the logic correctly, this would imply there won't be any calendar-based notification for them.

This means their holiday reminders wouldn't be working as intended. Not sure if this was changed when Blizzard moved to different reward structures (e.g., container instead of normal loot), so that's something that might need to be investigated first.

### PR DESCRIPTION
**Pull request by godejord**
Went over the list of holiday related items and added any missing holidayTextures. This closes #289.

### CODE REVIEW

**Comment by nickbayley** [comment]
Is it just me, or is "Big Love Rocket" now missing from the DB?

**Comment by godejord** [comment]
> Is it just me, or is "Big Love Rocket" now missing from the DB?

It seems to be lost. Probably related to the refactoring that was recently done. I mentioned it in the issue #289

**Comment by nickbayley** [comment]
Ah, I didn't see you post that in the issue. Yeh, seems it was lost here: https://github.com/SacredDuckwhale/Rarity/commit/0a69210c92058c6655341d33280d1989059a2633

**Comment by SacredDuckwhale** [comment]
Confirmed. I'll fix it independently of this PR, including the ``holidayTexture`` if needed. Thanks!

**Pull request merged**
