### PR TITLE
Updates for Shadowlands 9.0.1 API changes.

### PR DESCRIPTION
**Pull request by dbowden713**
Using the list created at: https://github.com/Stanzilla/WoWUIBugs/wiki/9.0.1-Consolidated-UI-Changes

### CODE REVIEW

**Comment by gaveer** [comment]
```
2x ...\Libs\LibQTip-1.0\LibQTip-1.0-46.lua:519: attempt to call method 'SetBackdrop' (a nil value)
[string "\Libs\LibQTip-1.0\LibQTip-1.0-46.lua"]:519: in function <...\Libs\LibQTip-1.0\LibQTip-1.0.lua:513>
[string "\Libs\LibQTip-1.0\LibQTip-1.0-46.lua"]:126: in function 'Acquire'
[string "@Rarity\Core\GUI.lua"]:1598: in function 'ShowTooltip'
[string "@Rarity\Core\GUI.lua"]:404: in function 'OnEnter'
[string "@BankStack\lib\LibDBIcon-1.0\LibDBIcon-1.0-43.lua"]:77: in function <...BankStack\lib\LibDBIcon-1.0\LibDBIcon-1.0.lua:60>
[string "=[C]:"]: in function 'oenter'
[string "@MBB\MBB-4.0.1.lua"]:466: in function <MBB\MBB.lua:448>

**Comment by dbowden713** [comment]
@gaveer Looks like that's an issue with LibQTip, which isn't part of this repo. Will probably have to wait for the authors of that library to fix it on their end.

**Comment by gaveer** [comment]
https://pastebin.com/DxRyHy9C 
LibQTip.lua

**Comment by SacredDuckwhale** [comment]
Thanks! I'll push an alpha release to see if everything's working with the updated LibQTip from WowAce. It should be included automatically by the packager.

Please let me know if there's more issues :)

**Pull request merged**
